<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.Testing" Version="13.2.3" />
      <PackageReference Include="WireMock.Net.Testcontainers" Version="2.3.0" />
      <PackageReference Include="xunit.v3.assert" Version="3.2.2" />
      <PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Synonms.Structur.Domain\Synonms.Structur.Domain.csproj" />
      <ProjectReference Include="..\Synonms.Structur.Api.Server\Synonms.Structur.Api.Server.csproj" />
    </ItemGroup>

</Project>
