<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="10.0.11">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NSwag.ApiDescription.Client" Version="14.7.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <OpenApiReference Include="../Synonms.Structur.Sample.Api/OpenApi/v1.json" OutputPath="StructurSampleClient.cs" Namespace="Synonms.Structur.Sample.ClientApi.OpenApi">
            <ClassName>StructurSampleOpenApiClient</ClassName>
            <CodeGenerator>NSwagCSharp</CodeGenerator>
            <Options> /JsonLibrary:SystemTextJson /UseBaseUrl:false /GenerateClientInterfaces:true /WrapResponses:true /ResponseClass:StructurSampleApiResponse /GenerateOptionalParameters:true /ExposeJsonSerializerSettings:true</Options>
        </OpenApiReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Synonms.Structur.Api.Client\Synonms.Structur.Api.Client.csproj" />
    </ItemGroup>

</Project>
