<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AspNetCore.HealthChecks.MongoDb" />
        <PackageReference Include="MongoDB.Bson" />
        <PackageReference Include="MongoDB.Driver" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Synonms.Structur.Api.Server\Synonms.Structur.Api.Server.csproj" />
      <ProjectReference Include="..\Synonms.Structur.Domain\Synonms.Structur.Domain.csproj" />
      <ProjectReference Include="..\Synonms.Structur.Infrastructure\Synonms.Structur.Infrastructure.csproj" />
    </ItemGroup>

</Project>
